### ISSUE TITLE
Can't get cache working as getter decorator (cache is not invalidating)

### ISSUE THREAD

**Issue by lifeart** [ember-polyfills/ember-cache-primitive-polyfill#17]
```js
function cachedGetter(klass, desc) {
  const cache = createCache(desc.get.bind(klass));
  desc.get = () => getValue(cache);
  return desc;
}

function cached(klass, _, desc) {
  if (typeof desc.get === "function") {
    return cachedGetter(klass, desc);
  }
  return desc;
}
```

test:
```js
  test("it works", (assert) => {
    class Foo {
      get counter() {
        if (!this.initial) {
          this.initial = 0;
        }
        this.initial++;
        return this.initial;
      }
      @tracked count = 0;
      @cached
      get value() {
        return this.count + this.counter;
      }
    }

    const item = new Foo();
    assert.deepEqual(item.value, 1, "memoized result returned correctly1");
    assert.deepEqual(item.value, 1, "memoized result returned correctly2");
    item.count++;
    assert.deepEqual(item.value, 3, "memoized result returned correctly3");
  });
```

![image](https://user-images.githubusercontent.com/1360552/84548939-7b1f8780-ad0f-11ea-9e76-ad03bce85185.png)

**Comment by pzuraq** [comment]
That's not correct usage of this primitive. To see how you would use this primitive to accomplish the goal you're trying to accomplish, see this PR: https://github.com/pzuraq/tracked-toolbox/pull/9

**Comment by lifeart** [comment]
@pzuraq thank you for references! My example not working because it create cache outside of tracking transaction?

**Comment by pzuraq** [comment]
You're binding `get()` to the prototype, not the instance, in your code. Caches need to be created _per instance_ that they are used in, since each individual instance may have a different value. That's what the WeakMap is for in the `@cached` decorator in `tracked-toolbox`.
